# syntax=docker/dockerfile:1

FROM oven/bun:1.3.14 AS base
WORKDIR /app

# --- deps ---
FROM base AS deps
COPY package.json bun.lock* bun.lockb* ./
# postinstall runs `prisma generate`; schema must exist before install.
COPY prisma ./prisma
RUN bun install --frozen-lockfile

# --- build ---
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# The Prisma client was generated by the deps stage postinstall; `generated/`
# is not part of the build context (see .dockerignore).
COPY --from=deps /app/generated ./generated
# Runtime env is injected by compose; the image build must not require it.
ENV SKIP_ENV_VALIDATION=1
RUN bun run build

# --- runtime ---
FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

CMD ["bun", "server.js"]